<?php
require 'config.php';
require('fpdf186/fpdf.php');

if (!isset($_GET['prescription_id'])) {
    die('Prescription ID required');
}

$prescription_id = intval($_GET['prescription_id']);

// Fetch prescription details
$sql = "SELECT 
    p.*,
    CONCAT(pat.first_name, ' ', pat.last_name) as patient_name,
    pat.gender,
    CONCAT(d.first_name, ' ', d.last_name) as doctor_name,
    d.specialty,
    d.hospital,
    d.license_no,
    a.appointment_date
FROM prescriptions p
JOIN patients pat ON p.patient_id = pat.patient_id
JOIN doctors d ON p.doctor_id = d.doctor_id
JOIN appointments a ON p.appointment_id = a.appointment_id
WHERE p.prescription_id = ?";

$stmt = $conn->prepare($sql);
$stmt->bind_param("i", $prescription_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die('Prescription not found');
}

$prescription = $result->fetch_assoc();
$stmt->close();

// Fetch medicines
$sql_med = "SELECT * FROM prescription_medicines WHERE prescription_id = ? ORDER BY medicine_id ASC";
$stmt_med = $conn->prepare($sql_med);
$stmt_med->bind_param("i", $prescription_id);
$stmt_med->execute();
$result_med = $stmt_med->get_result();

$medicines = [];
while ($row = $result_med->fetch_assoc()) {
    $medicines[] = $row;
}
$stmt_med->close();
$conn->close();

// Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// Header - Doctor Info
$pdf->SetFont('Arial', 'B', 18);
$pdf->SetTextColor(5, 150, 105);
$pdf->Cell(0, 10, 'Dr. ' . $prescription['doctor_name'], 0, 1);

$pdf->SetFont('Arial', '', 11);
$pdf->SetTextColor(70, 70, 70);
$pdf->Cell(0, 6, $prescription['specialty'], 0, 1);
$pdf->Cell(0, 6, $prescription['hospital'], 0, 1);
$pdf->Cell(0, 6, 'License No: ' . $prescription['license_no'], 0, 1);

$pdf->Line(10, $pdf->GetY() + 3, 200, $pdf->GetY() + 3);
$pdf->Ln(8);

// Patient Details
$pdf->SetFont('Arial', 'B', 12);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(0, 7, 'Patient Details', 0, 1);

$pdf->SetFont('Arial', '', 10);
$pdf->Cell(50, 6, 'Name:', 0, 0);
$pdf->Cell(0, 6, $prescription['patient_name'], 0, 1);
$pdf->Cell(50, 6, 'Gender:', 0, 0);
$pdf->Cell(0, 6, $prescription['gender'], 0, 1);
$pdf->Cell(50, 6, 'Date:', 0, 0);
$pdf->Cell(0, 6, date('d M Y', strtotime($prescription['prescription_date'])), 0, 1);
$pdf->Ln(5);

// Diagnosis
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 7, 'Diagnosis', 0, 1);
$pdf->SetFont('Arial', '', 10);
$pdf->MultiCell(0, 6, $prescription['diagnosis']);
$pdf->Ln(3);

// Rx Symbol
$pdf->SetFont('Arial', 'B', 20);
$pdf->SetTextColor(5, 150, 105);
$pdf->Cell(0, 10, 'Rx', 0, 1);
$pdf->Ln(2);

// Medicines Table
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFillColor(5, 150, 105);
$pdf->Cell(10, 8, '#', 1, 0, 'C', true);
$pdf->Cell(50, 8, 'Medicine', 1, 0, 'L', true);
$pdf->Cell(35, 8, 'Dosage', 1, 0, 'L', true);
$pdf->Cell(40, 8, 'Frequency', 1, 0, 'L', true);
$pdf->Cell(25, 8, 'Duration', 1, 0, 'L', true);
$pdf->Cell(30, 8, 'Instructions', 1, 1, 'L', true);

$pdf->SetFont('Arial', '', 9);
$pdf->SetTextColor(0, 0, 0);

foreach ($medicines as $index => $med) {
    $pdf->Cell(10, 7, ($index + 1), 1, 0, 'C');
    $pdf->Cell(50, 7, $med['medicine_name'], 1, 0);
    $pdf->Cell(35, 7, $med['dosage'], 1, 0);
    $pdf->Cell(40, 7, $med['frequency'], 1, 0);
    $pdf->Cell(25, 7, $med['duration'], 1, 0);
    $pdf->Cell(30, 7, $med['instructions'], 1, 1);
}

$pdf->Ln(5);

// Additional Notes
if (!empty($prescription['notes'])) {
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(0, 7, 'Additional Notes:', 0, 1);
    $pdf->SetFont('Arial', '', 10);
    $pdf->MultiCell(0, 6, $prescription['notes']);
    $pdf->Ln(3);
}

// Signature
$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 10);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(0, 6, 'Doctor\'s Signature: _______________________', 0, 1);
$pdf->Ln(5);

// Footer
$pdf->SetFont('Arial', 'I', 8);
$pdf->SetTextColor(150, 150, 150);
$pdf->Cell(0, 5, 'Generated by Doc.Link - Digital Health Platform', 0, 1, 'C');
$pdf->Cell(0, 5, 'Prescription ID: ' . $prescription_id, 0, 1, 'C');

// Output
$pdf->Output('D', 'Prescription_' . $prescription_id . '.pdf');
?>
